
package electricity.billing.system.StudentMenus;
import electricity.billing.system.Conn;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.lang.String;
public class MarksPane extends javax.swing.JInternalFrame {
    Double sem1,sem2,sem3,sem4,sem5,sem6,sem7,sem8;
    String tsem1,tsem2,tsem3,tsem4,tsem5,tsem6,tsem7,tsem8;
    ResultSet rs;
    String user_roll;
    double total;
    private ResultSet marks_set;
    double tot_marks;
    Double tot_per;
    public MarksPane() {
        get_full_marks();
        initComponents();
        add_details();
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
    
        public MarksPane(ResultSet data) {
        
        try{
            rs = data;
            user_roll = rs.getString(1);
        }
        catch(Exception e){
            System.out.println("Error : "+e);
        }
        get_full_marks();
        initComponents();
        
        add_details();
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluatorDouble1 = new org.jdesktop.core.animation.timing.evaluators.EvaluatorDouble();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MarksTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(5000, 5000));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(5000, 5000));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Marks Panel");

        MarksTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 12, 148)));
        MarksTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MarksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6", "Semester 7", "Semester 8"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MarksTable.setColumnSelectionAllowed(true);
        MarksTable.setGridColor(new java.awt.Color(87, 12, 148));
        MarksTable.setSelectionBackground(new java.awt.Color(204, 204, 255));
        MarksTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(MarksTable);
        MarksTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (MarksTable.getColumnModel().getColumnCount() > 0) {
            MarksTable.getColumnModel().getColumn(0).setResizable(false);
            MarksTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            MarksTable.getColumnModel().getColumn(1).setResizable(false);
            MarksTable.getColumnModel().getColumn(1).setPreferredWidth(15);
            MarksTable.getColumnModel().getColumn(2).setResizable(false);
            MarksTable.getColumnModel().getColumn(2).setPreferredWidth(15);
            MarksTable.getColumnModel().getColumn(3).setResizable(false);
            MarksTable.getColumnModel().getColumn(3).setPreferredWidth(15);
            MarksTable.getColumnModel().getColumn(4).setResizable(false);
            MarksTable.getColumnModel().getColumn(4).setPreferredWidth(15);
            MarksTable.getColumnModel().getColumn(5).setResizable(false);
            MarksTable.getColumnModel().getColumn(5).setPreferredWidth(15);
            MarksTable.getColumnModel().getColumn(6).setResizable(false);
            MarksTable.getColumnModel().getColumn(6).setPreferredWidth(15);
            MarksTable.getColumnModel().getColumn(7).setResizable(false);
            MarksTable.getColumnModel().getColumn(7).setPreferredWidth(15);
        }

        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Toral CGPA : ");

        jLabel3.setText(Double.toString(tot_marks));

        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Equivalent Percentage :");

        jLabel5.setText(tot_per.toString());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(4062, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4578, 4578, 4578))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 5006, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(5000, 5000));
    }// </editor-fold>//GEN-END:initComponents

    private void add_details(){
        try{
                String tbdata[] = {tsem1,tsem2,tsem3,tsem4,tsem5,tsem6,tsem7,tsem8};
                DefaultTableModel tb1 = (DefaultTableModel)MarksTable.getModel();
                tb1.addRow(tbdata);
        }
            
        catch(Exception e){
            System.out.println("Error : "+e.getMessage());
        }
    }
    
    private void get_full_marks(){
        Double count=0.0;
        try{
            Conn c = new Conn();
            String query = "select * from marks_panel where univ_roll = "+user_roll;
            ResultSet tot = c.s.executeQuery(query);
            while(tot.next()){
                tsem1 =tot.getString(2);
                if(tsem1!=null) count+=1.0;
                sem1 = tsem1==null ? 0.0:Double.parseDouble(tsem1);

                tsem2 =tot.getString(3);
                if(tsem2!=null) count+=1.0;
                sem2 = tsem2==null ? 0.0:Double.parseDouble(tsem2);
                
                tsem3 =tot.getString(4);
                if(tsem3!=null) count+=1.0;
                sem3 = tsem3==null ? 0.0:Double.parseDouble(tsem3);
                
                tsem4 =tot.getString(5);
                if(tsem4!=null) count+=1.0;
                sem4 = tsem4==null ? 0.0:Double.parseDouble(tsem4);
                
                tsem5 =tot.getString(6);
                if(tsem5!=null) count+=1.0;
                sem5 = tsem5==null ? 0.0:Double.parseDouble(tsem5);
                
                tsem6 =tot.getString(7);
                if(tsem6!=null) count+=1.0;
                sem6 = tsem6==null ? 0.0:Double.parseDouble(tsem6);

                tsem7 =tot.getString(8);
                if(tsem7!=null) count+=1.0;
                sem7 = tsem7==null ? 0.0:Double.parseDouble(tsem7);
                
                tsem8 =tot.getString(9);
                if(tsem8!=null) count+=1.0;
                sem8 = tsem8==null ? 0.0:Double.parseDouble(tsem8);
                break;
            }
            
            tot_marks = (sem1+sem2+sem3+sem4+sem5+sem6+sem7+sem8)/count;
            tot_marks = Math.round(tot_marks * 100)/100.00;
            tot_per = (double)(Math.round(tot_marks * 9.09 * 100)/100);
            
        }
        catch(Exception e){
            System.out.println("error bc");
            System.out.println(e.getMessage());
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MarksTable;
    private org.jdesktop.core.animation.timing.evaluators.EvaluatorDouble evaluatorDouble1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
