/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricity.billing.system;
import java.sql.*;
import javax.swing.JOptionPane;


public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBar = new javax.swing.JPanel();
        CompanyName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CompanyMoto1 = new javax.swing.JLabel();
        LoginDashboard = new javax.swing.JPanel();
        UserName = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        UserNameIcon = new javax.swing.JLabel();
        PasswordIcon = new javax.swing.JLabel();
        RegisterButton = new rojerusan.RSButtonHover();
        ExitButton = new rojerusan.RSButtonHover();
        LoginButton = new rojerusan.RSButtonHover();
        DashBoardHeading = new javax.swing.JLabel();
        FacaultyLoginMessage = new javax.swing.JLabel();
        FacaultyLoginPath = new javax.swing.JLabel();
        VersionName = new javax.swing.JLabel();
        CompanyMoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideBar.setBackground(new java.awt.Color(87, 12, 148));
        SideBar.setPreferredSize(new java.awt.Dimension(300, 400));
        SideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CompanyName.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        CompanyName.setForeground(new java.awt.Color(255, 255, 255));
        CompanyName.setText("AMSC 2022");
        SideBar.add(CompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/adminLoginSticker.png"))); // NOI18N
        SideBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 260, 280));

        CompanyMoto1.setForeground(new java.awt.Color(255, 255, 255));
        CompanyMoto1.setText("Best college management software");
        SideBar.add(CompanyMoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 220, -1));

        getContentPane().add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 400));

        LoginDashboard.setBackground(new java.awt.Color(255, 255, 255));
        LoginDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        UserName.setForeground(new java.awt.Color(36, 5, 61));
        UserName.setText("Employee Number");
        UserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(87, 12, 148)));
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        LoginDashboard.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 270, 50));

        jPassword.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jPassword.setForeground(new java.awt.Color(36, 5, 61));
        jPassword.setText("Password");
        jPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(87, 12, 148)));
        jPassword.setPreferredSize(new java.awt.Dimension(88, 22));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        LoginDashboard.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 270, 30));

        UserNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login_Username_Icon.png"))); // NOI18N
        LoginDashboard.add(UserNameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 50));

        PasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login_Password_2.png"))); // NOI18N
        LoginDashboard.add(PasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 40));

        RegisterButton.setBackground(new java.awt.Color(255, 255, 255));
        RegisterButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 12, 148)));
        RegisterButton.setText("New \nEmployee ?");
        RegisterButton.setColorHover(new java.awt.Color(87, 12, 148));
        RegisterButton.setColorText(new java.awt.Color(87, 12, 148));
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        LoginDashboard.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 120, -1));

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 12, 148)));
        ExitButton.setText("X");
        ExitButton.setColorHover(new java.awt.Color(87, 12, 148));
        ExitButton.setColorText(new java.awt.Color(87, 12, 148));
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        LoginDashboard.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 30, 30));

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 12, 148)));
        LoginButton.setText("Login");
        LoginButton.setColorHover(new java.awt.Color(87, 12, 148));
        LoginButton.setColorText(new java.awt.Color(87, 12, 148));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginDashboard.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 120, -1));

        DashBoardHeading.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        DashBoardHeading.setForeground(new java.awt.Color(87, 12, 148));
        DashBoardHeading.setText("Admin Login");
        LoginDashboard.add(DashBoardHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 230, 50));

        FacaultyLoginMessage.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        FacaultyLoginMessage.setText("Are you a Student ? Login from ");
        LoginDashboard.add(FacaultyLoginMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 180, -1));

        FacaultyLoginPath.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        FacaultyLoginPath.setForeground(new java.awt.Color(87, 12, 148));
        FacaultyLoginPath.setText("here");
        FacaultyLoginPath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacaultyLoginPathMouseClicked(evt);
            }
        });
        LoginDashboard.add(FacaultyLoginPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        VersionName.setText("Version : 0.0.1");
        LoginDashboard.add(VersionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 90, -1));

        CompanyMoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CompanyMoto.setForeground(new java.awt.Color(87, 12, 148));
        CompanyMoto.setText("Only administators and teachers can enter");
        LoginDashboard.add(CompanyMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 280, -1));

        getContentPane().add(LoginDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 520, 400));

        setSize(new java.awt.Dimension(800, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
        setVisible(false);
        dispose();
        new Admin_Register1().setVisible(true);
    }//GEN-LAST:event_RegisterButtonMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        String roll = UserName.getText();
        String pass = String.copyValueOf(jPassword.getPassword());
        try{    
            Conn c = new Conn();
            String query = "Select * from employee_register where emp_id = '"+roll+"' and pass = '"+pass+"'";
            ResultSet data = c.s.executeQuery(query);
            
            if(data.next()){
                System.out.println(data.getString(2));
                this.setVisible(false);
                new AdminDashBoard1(data).setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Credentials");
                UserName.setText("");
                jPassword.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e);
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void FacaultyLoginPathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacaultyLoginPathMouseClicked
        dispose();
        new LoginUI().setVisible(true);
    }//GEN-LAST:event_FacaultyLoginPathMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompanyMoto;
    private javax.swing.JLabel CompanyMoto1;
    private javax.swing.JLabel CompanyName;
    private javax.swing.JLabel DashBoardHeading;
    private rojerusan.RSButtonHover ExitButton;
    private javax.swing.JLabel FacaultyLoginMessage;
    private javax.swing.JLabel FacaultyLoginPath;
    private rojerusan.RSButtonHover LoginButton;
    private javax.swing.JPanel LoginDashboard;
    private javax.swing.JLabel PasswordIcon;
    private rojerusan.RSButtonHover RegisterButton;
    private javax.swing.JPanel SideBar;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel UserNameIcon;
    private javax.swing.JLabel VersionName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword;
    // End of variables declaration//GEN-END:variables
}
