/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electricity.billing.system;

/**
 *
 * @author abhis
 */
public class Loading extends javax.swing.JFrame {
     
    
    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainBackground = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("AMSC Solutions");
        MainBackground.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 340, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loading2.gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        MainBackground.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 250, 370, 130));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/anim2.gif"))); // NOI18N
        MainBackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 420, 350));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Version 0.0.1");
        MainBackground.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg_black.jpg"))); // NOI18N
        MainBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
